language: node_js
node_js:
  - "8.1.2"
env:
  - CXX=g++-4.8
notifications:
  slack: niobi:WW01STIxrmCAQfbm9FZzW30v
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8